### ISSUE TITLE
CHORDS data not available...

### ISSUE THREAD

**Issue by smrgeoinfo** [earthcube2021/ec21_dye_etal#1]
the notebook opens, when get to download data from CHORDS (at 5.1. Select the instrument ID and the start and end date of the data to be processed and analyzed), the csv files are empty.  no Data

**Comment by mdye** [comment]
Thank you for reporting this. The data for the default date was no longer stored on the CHORDS portal. A csv file containing those data has been added to the repository so the notebook will execute as expected using the default configuration.

**Comment by smrgeoinfo** [comment]
thanks for the fix Mike
